// <auto-generated />
using MiApiSQLite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLibros.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20251016151314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MiApiSQLite.Models.Book", b =>
                {
                    b.Property<string>("isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("image_url_l")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("image_url_m")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("image_url_s")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year_of_publication")
                        .HasColumnType("INTEGER");

                    b.HasKey("isbn");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
